[package]
name = "example"
version = "0.1.0"
authors = ["Felix KohlgrÃ¼ber <felix.kohlgrueber@gmail.com>"]
edition = "2018"


[dependencies]
parse_pattern = { path = "../../parse-pattern" }
lazy_static = "1.2.0"