[package]
name = "pattern_tree"
version = "0.1.0"
authors = ["Felix KohlgrÃ¼ber <felix.kohlgrueber@gmail.com>"]
edition = "2018"

[dependencies]
gen_pattern_tree = { path = "../gen_pattern_tree" }
lazy_static = "1.2.0"

[lib]
path = "pattern_tree.rs"