[package]
name = "pattern-func-lib"
version = "0.1.0"
authors = ["Felix Kohlgr√ºber <felix.kohlgrueber@gmail.com>"]
edition = "2018"

[dependencies]
pattern-func = { path = "../pattern-func" }


[lib]
proc-macro = true
path = "src/pattern_func_lib.rs"
doctest = false