[package]
name = "pattern"
version = "0.1.0"
authors = ["Felix KohlgrÃ¼ber <felix.kohlgrueber@gmail.com>"]
edition = "2018"

[dependencies]

pattern-macro = { path = "../pattern-macro" }
pattern-match = { path = "../pattern-match" }

[lib]
doctest = false
path = "src/pattern.rs"